name: 'Terraform Action'
description: 'Run Terraform to deploy infrastructure'
author: 'Pradipbabar'
inputs:
  tfvars-file:
    description: 'Path to the .tfvars file'
    required: true
runs:
  using: 'docker'
  image: 'hashicorp/terraform:latest'
branding:
  icon: 'cloud'
