name: 'Terraform Action'
description: 'Run Terraform to deploy infrastructure'
author: 'Pradipbabar'
inputs:
  tfvars:
    required: true
runs:
  using: "docker"
  image: "Dockerfile"
  args: 
    - "terraform"
    - "show"
    # - "validate"
    # - "terraform"
    # - "validate"
    # - "-var-file=${{ inputs.tfvars }}"
