name: 'Terraform Action'
description: 'Run Terraform to deploy infrastructure'
author: 'Pradipbabar'
inputs:
  tfvars:
    required: true
  aws_access_key_id:
    description: 'AWS Access Key ID from GitHub Secrets'
    required: true
  aws_secret_access_key:
    description: 'AWS Secret Access Key from GitHub Secrets'
    required: true
  aws_default_region:
    description: 'AWS Default Region from GitHub Secrets'
    required: true
runs:
  using: "docker"
  image: "Dockerfile"
  # args: 
    #  _ ${{ inputs.tfvars }}
    #  _ ${{ inputs.aws _access _key _id }}
    #  _ ${{ inputs.aws _secret _access _key }}
    #  _ ${{ inputs.aws _default _region }}

