#!/bin/sh -l
cat $INPUT_TFVARS
echo "$INPUT_AWS-ACCESS-KEY-ID" >> $GITHUB_OUTPUT
echo "$INPUT_AWS-SECRET-ACCESS-KEY" >> $GITHUB_OUTPUT
echo "$INPUT_AWS-DEFAULT-REGION" >> $GITHUB_OUTPUT
time=$(date)
echo "time=$time" >> $GITHUB_OUTPUT

