name: Test 
on: [push]

jobs:
  test-action:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: run local actions/checkout
        uses: ./
        with:
          tfvars: var.tfvars
          aws-access-key-id: cdde
          aws-secret-access-key: xxy
          aws-default-region: us-east-1

      - name: get the Outputs
        run:  echo "The time was ${{ steps.hello.outputs.time }}"  