name: Test 
on: [push]

jobs:
  test-action:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: make tfvar file executable
        run: chmod +x ./var.tfvars
      
      - name: run local actions
        uses: ./
        with:
          tfvars: ./var.tfvars
          aws_access_key_id: cdde
          aws_secret_access_key: xxy
          aws_default_region: us-east-1

      - name: get the Outputs
        run:  echo "The time was ${{ steps.hello.outputs.time }}"  