name: Test 
on: [push]

jobs:
  test-action:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: run local actions/checkout
        uses: ./
        with:
          tfvars: ./var.tfvars
          aws-access-key-id: ''
          aws-secret-access-key: ''
          aws-default-region: 'us-east-1'